config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "articles#search"
  get "/search", to: "articles#search", as: "search"
  get "logs_for_query/:id", to: "articles#query_logs", as: "logs_for_query"
  get "/user_logs", to: "articles#user_logs", as: "user_logs"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search, against: %i[title content], using: { tsearch: { prefix: true, normalization: 8 } }
  validates :title, presence: true
  validates :content, presence: true
end

app/models/search_log.rb
class SearchLog < ApplicationRecord
  belongs_to :search_query

  validates :ip_address, presence: true
  validates :results_count, numericality: { only_integer: true }
end

app/models/search_query.rb
class SearchQuery < ApplicationRecord
  has_many :search_logs
  validates :query, presence: true, uniqueness: true

  def self.track(query)
    query = query.downcase
    search_query = find_or_initialize_by(query: query)
    search_query.count ||= 0
    search_query.count += 1
    search_query.save!
    search_query
  end

  def log_search(ip, payload)
    search_logs.create!(
      ip_address: ip,
      results_count: payload["results_count"],
      created_at: payload["created_at"]
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def search
    @pagy_queries, @queries = pagy(SearchQuery.all.order(count: :desc, created_at: :desc), items: 6)
    @logs = SearchLog.none
    @users = SearchLog.distinct.pluck(:ip_address).sort
    @pagy = nil
    @articles = Article.none
    if params_exist?
      articles_query = Article.search(search_params)
      results_count = articles_query.count
      @pagy, @articles = pagy(articles_query, items: 6)
      SearchService.push_to_redis(REDIS, { creator: request.remote_ip, value: search_params, results_count: results_count })
    end
    if turbo_frame_request?
        render partial: "results", locals: { articles: @articles,  term: search_params }
    else
      render "index", locals: { articles: @articles, term: "" }
    end
  end

  def query_logs
     @search_query = SearchQuery.find(params[:id])
     # @logs = @search_query.search_logs
     @logs = @search_query.search_logs.group_by(&:ip_address)
    respond_to do |format|
      format.turbo_stream
    end
  end
  def user_logs
    @selected_ip =  params[:ip]
    @user_logs = SearchLog
                    .includes(:search_query)
                    .where(ip_address: params[:ip])
                    .group_by(&:search_query_id)
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def params_exist?
    params[:term].present?
  end
  def search_params
    params_exist? ? params[:term].strip : ""
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="p-4 border rounded-lg shadow-sm">
  <h3 class="text-xl font-semibold"><%= article.title %></h3>
  <p class="text-gray-600"><%= article.content %></p>
</div>

app/views/articles/_logs.html.erb
<div class="max-h-screen overflow-y-auto">
  <%= turbo_frame_tag "logs" do %>
    <% if @logs.present? %>
      <h3>Result for <strong><%= @search_query.query %></strong></h3>
        <% @logs.each do |ip, logs| %>
          <div class="mb-6 p-4 bg-white shadow rounded-lg">
            <h3 class="text-lg font-semibold text-blue-700">User : <%= ip %></h3>
            <ul class="list-disc ml-6 text-gray-700 mt-2">
              <% logs.each do |log| %>
                <li class="pb-2">
                  <%= puts log.to_json %>
                  <strong>Logged at:</strong> <%= time_ago_in_words(log.created_at) %> ago<br>
                  <strong>Results:</strong> <%= log.results_count %> articles<br>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>
      <% else %>
      <h3>Found  0</h3>
    <% end %>
  <% end %>
</div>

app/views/articles/_results.html.erb
<%= turbo_frame_tag "search_results" do %>
  <% if params[:term].present? && @pagy.present? && @pagy.count > 0 %>
    <div class="px-6 py-4 shadow">
      <h2 class="font-bold text-xl mb-2"><%= @pagy.count %> Results</h2>
      <div class="flex items-center justify-center w-full">
        <%= raw pagy_nav(@pagy, page_param: :page_articles) %>
      </div>
      <p class="text-center mt-6 text-gray-500"><%= raw pagy_info(@pagy) %></p>
    </div>
  <% end %>

  <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
    <% @articles.each do |article| %>
      <div class="px-4 py-2 border border-gray-200 shadow-sm">
        <div class="px-6 py-4">
          <h2 class="font-bold text-xl mb-2">
            <%= highlight(article.title, params[:term].to_s.split) %>
          </h2>
          <p class="text-gray-700 text-base">
            <%= highlight(article.content, params[:term].to_s.split) %>
          </p>
        </div>
      </div>
    <% end %>
  </div>

  <% if @pagy.present? && @pagy.count > 0 %>
    <div class="flex items-center justify-center mt-6 w-full">
      <%= raw pagy_nav(@pagy, page_param: :page_articles) %>
    </div>
  <% end %>
<% end %>

app/views/articles/_select_user.html.erb
<div data-controller="query-log" data-turbo_action="advance">
  <label for="user_id" class="block mb-2 text-sm font-medium text-gray-700">Select User</label>

  <%= select_tag :user_id,
                 options_for_select(@users),
                 prompt: "Choose IP Address",
                 data: { action: "change->query-log#loadbyuser", url: user_logs_path },
                 class: "p-2 border border-gray-300 rounded shadow-sm" %>
</div>

app/views/articles/_user_logs.html.erb
<div class="max-h-screen overflow-y-auto">
  <%= turbo_frame_tag "user_logs" do %>
    <% if @user_logs.present? %>
      <h3>Found  <%= @user_logs.count %></h3>
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        <% @user_logs.each do |query_id, logs| %>
          <div class="p-4 bg-white rounded-xl shadow-sm border border-gray-100">
            <h2 class="text-lg font-semibold text-gray-800 mb-2">
              🔍 Query: <%= logs.first.search_query.query %>
            </h2>
            <ul class="list-disc pl-5 space-y-1 text-sm text-gray-600">
              <% logs.each do |log| %>
                <li>
            <span class="text-gray-700 font-medium">
              <%= log.created_at.strftime("%b %d, %Y %H:%M") %>
            </span>
                  — <%= log.results_count %> article(s) found
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
      <% else %>
      <h3>Found  0</h3>
    <% end %>
  <% end %>
</div>

app/views/articles/index.html.erb
<div class="max-w-7xl mx-auto px-4 py-10">
  <div data-turbo-permanent>
    <%= form_with url: search_path,
                  id: 'search',
                  method: :get,
                  class: 'bg-white p-6 rounded-xl shadow-sm max-w-2xl mx-auto',
                  data: {
                    controller: "search",
                    turbo_action: "advance",
                    turbo_frame: "search_results"
                  } do |form| %>
      <%= form.text_field :term,
                          value: params[:term],
                          placeholder: "Search articles...",
                          autocomplete: "off",
                          autofocus: true,
                          class: "w-full px-4 py-2 border border-gray-300 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500",
                          data: {
                            action: "input->search#search"
                          } %>
    <% end %>
  </div>

  <div class="mt-10">
    <%= render "results", articles: @articles, term: params[:term] %>
  </div>
  <div class="flex items-center justify-between mb-6 shadow-sm p-2 gap-2">
    <h4 class="font-bold text-blue-700">Refresh this page in 20 seconds and you will see the new stats (in the future this will be dynamic)</h4>
    <div>
      <%= link_to 'Refresh', search_path, class: "inline-flex items-center  px-2 py-2 bg-gray-900 text-white border border-gray-300 rounded-md text-sm  hover:bg-gray-600 transition" %>
    </div>
  </div>

  <div data-controller="query-log" class="flex flex-col items-center w-full justify-center">
    <div class="flex justify-center items-center gap-8 w-full">
      <label class="flex items-center gap-2 text-gray-700">
        <input type="radio"
               name="log_view"
               value="general"
               data-action="query-log#toggle"
               checked="checked"
               class="form-radio text-blue-600" />
        General
      </label>

      <label class="flex items-center gap-2 text-gray-700">
        <input type="radio"
               name="log_view"
               value="ip"
               data-action="query-log#toggle"
               class="form-radio text-blue-600" />
        By IP/User
      </label>
    </div>
    <div class="flex flex-col w-full">
      <div data-query-log-target="generalSection" class="w-full mt-8">
        <!-- General Queries Section -->
        <div class="grid grid-cols-1 md:grid-cols-2 gap-10 mt-12">
          <!-- Queries Section -->
          <div class="space-y-6" data-controller="query-log" data-turbo_action="advance">
            <h2 class="text-xl font-bold text-blue-700">General Searches</h2>
            <% if @pagy_queries.present? && @pagy_queries.count > 0 %>
              <div class="p-4 bg-white shadow-sm rounded-xl">
                <h3 class="font-semibold text-gray-700 mb-2">
                  <%= @pagy_queries.count %> Queries Found
                </h3>
                <div class="flex justify-center">
                  <%= raw pagy_nav(@pagy_queries, page_param: :page_queries) %>
                </div>
                <p class="text-sm text-center mt-4 text-gray-500">
                  <%= raw pagy_info(@pagy_queries) %>
                </p>
              </div>
            <% end %>

            <ul class="space-y-4">
              <% @queries.each do |query| %>
                <li id="query-id-<%= query.id %>"
                    class="flex justify-between items-center p-4 bg-white border border-gray-200 rounded-lg hover:shadow transition">
                  <div>
                    <p class="text-base font-semibold text-gray-800"><%= query.query %></p>
                    <p class="text-sm text-gray-500"><%= query.count %> logs</p>
                  </div>
                  <button class="flex items-center gap-2 px-3 py-1.5 text-sm bg-blue-600 text-white rounded-md hover:bg-blue-700 focus:ring-2 focus:ring-blue-400"
                          data-action="click->query-log#loadLogs"
                          data-search="<%= query.id %>"
                          data-url="<%= logs_for_query_path(query.id) %>"
                          data-query-log-target="queryLog">
                    <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    View Logs
                  </button>
                </li>
              <% end %>
            </ul>
          </div>
          <!-- Logs Section -->
          <div class="space-y-6">
            <h2 class="text-xl font-bold text-blue-700">
              Logs for Selected Query
            </h2>
            <div data-query-log-target="logs">
              <%= render "logs" %>
            </div>
          </div>
        </div>
      </div>

      <div data-query-log-target="ipSection" class="w-full mt-8 hidden">
        <!-- Logs by User/IP Section -->
        <div class="grid grid-cols-1 gap-10 mt-12">
          <div class="space-y-6">
            <p class="text-sm text-gray-500 mb-2">Select user to view associated search logs:</p>
            <%= render "select_user", list: @users %>
          </div>
          <div class="space-y-6">
            <p class="text-sm text-gray-500 mb-2">Select user to view associated search logs:</p>
            <%= render "user_logs" %>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/articles/query_logs.turbo_stream.erb
<%= turbo_stream.replace("logs") do %>
  <%= render partial: "logs", locals: { logs: @logs, search_query: @search_query } %>
<% end %>

app/views/articles/search.html.erb
  <% if @articles.any? %>
    <% @articles.each do |article| %>
      <div class="p-4 border rounded-lg shadow-sm">
        <h3 class="text-xl font-semibold"><%= article.title %></h3>
        <p class="text-gray-600"><%= article.content %></p>
      </div>
    <% end %>
  <% else %>
    <p class="text-gray-500">No articles found==============</p>
  <% end %>

app/views/articles/user_logs.turbo_stream.erb
<%= turbo_stream.replace("user_logs") do %>
  <%= render partial: "user_logs", locals: { user_logs: @user_logs, selected_ip: @selected_ip } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Search Metrics" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%#= stylesheet_link_tag  :all, "pagy", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>